program: /project/monkey_training/hyper_params_search.py
name: sweep_brcnn_new
method: bayes
metric: 
  goal: maximize
  name: val/corr
parameters: 
  lr_init:
    values: [0.001]
  batch_size: 
    values: [4, 8, 16]
  upsampling: 
    values: [1,2]
  rot_eq_batch_norm: 
    values: [True]
  depth_separable: 
    values: [True, False]
  hidden_channels:
    values: [4, 8]
  hidden_kern: 
    values: [7,9]
  input_kern: 
    values: [3,5]
  layers: 
    values: [5, 6, 7]
  gamma_hidden:
    values: [0.001, 0.0001, 0.00001, 0]
  gamma_input: 
    values: [0.001, 0.0001, 0.00001, 0]
  init_sigma_range: 
    values: [0.1, 0.2]
  fine_tune: 
    values: [None, 'core']

  



  